openapi: 3.0.3
info:
  version: 1.0.0-alpha.1
  title: 'blah'
tags:
  - name: Payment
    description: Payment

paths:
  /accounts:
    get:
      description: 'List Accounts'
      operationId: list-accounts
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MPesaAccount'
    post:
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MPesaAccountRequest'
      responses:
        200:
          description: ''

  /payments:
    get:
      description: ''
      operationId: list-payments
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/IncomingMPesaPayment'
                    - $ref: '#/components/schemas/OutgoingMPesaPayment'
    post:
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/IncomingMPesaPaymentRequest'
                - $ref: '#/components/schemas/OutgoingMPesaPaymentRequest'
      responses:
        200:
          description: ''
    
  /payments/{paymentId}:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      operationId: get-payment
      description: ''
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                  oneOf:
                  - $ref: '#/components/schemas/IncomingMPesaPayment'
                  - $ref: '#/components/schemas/OutgoingMPesaPayment'
    patch:
      description: ''
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                reference:
                  type: string
      responses:
        200:
          description: ''

  /payments/{paymentId}/refund:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      operationId: refund-payment
      description: ''
      responses:
        200:
          description: ''
    
  /payments/{paymentId}/complete:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      operationId: complete-payment
      description: ''
      responses:
        200:
          description: ''
    
  /payments/{paymentId}/cancel:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      operationId: cancel-payment-request
      description: ''
      responses:
        200:
          description: ''
  /payments/{paymentId}/status:
    parameters:
      - name: paymentId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      description: ''
      responses:
        200:
          description: ''
  /accounts/{accountId}/details:
    parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      description: ''
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MPesaAccountDetails'
    patch:
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MPesaAccountDetails'
      responses:
        200:
          description: ''
  /credentials:
    post:
      description: ''
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credentials'
    get:
      description: ''
      responses:
        200:
          description: ''
components:
  schemas:
    MPesaAccountRequest:
      type: object
      properties:
        type:
          type: string
          enum: [mpesa]
        name:
          type: string
        details:
          type: object
          properties:
            api_key: 
              type : string
            public_key:
              type: string
            security_credential:
              type: string
            initiator_identifier:
              type: string
          required:
            - api_key
            - public_key
            - security_credential
            - initiator_identifier
      required:
        - type
        - name
        - details
    MPesaAccount:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [mpesa]
        name:
          type: string
      required:
        - type
        - name
        - details
    MPesaAccountDetails:
      type: object
      properties:
        api_key: 
          type : string
        public_key:
          type: string
        security_credential:
          type: string
        initiator_identifier:
          type: string
      required:
        - api_key
        - public_key
        - security_credential
        - initiator_identifier

    IncomingMPesaPaymentRequest:
      type: object
      properties:
        method:
          type: string
          enum:
            - mpesa
        account:
          type: string
          format: uuid
        source:
          type: object
          properties:
            number:
              type: string
        amount:
          type: number
        reference:
          type: string
        autocomplete:
          type: boolean
      required:
        - method
        - account
        - amount
    OutgoingMPesaPaymentRequest:
      type: object
      properties:
        method:
          type: string
          enum:
            - mpesa
        account:
          type: string
          format: uuid
        destination:
          type: object
          properties:
            type: 
              type: string
              enum: 
              - phone
              - business
            number:
              type: string
        amount:
          type: number
        reference:
          type: string
        autocomplete:
          type: boolean
      required:
        - method
        - account
        - amount
    IncomingMPesaPayment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - pending
            - complete
        account:
          type: string
          format: uuid
        method:
          type: string
          enum:
            - mpesa
        source:
          type: object
          properties:
            number:
              type: string
        amount:
          type: number
        reference:
          type: string
    OutgoingMPesaPayment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
          enum:
            - pending
            - complete
        account:
          type: string
          format: uuid
        method:
          type: string
          enum:
            - mpesa
        destination:
          type: object
          properties:
            type: 
              type: string
              enum: 
              - phone
              - business
            number:
              type: string
        amount:
          type: number
        reference:
          type: string
    Credentials:
      oneOf:
        - $ref: '#/components/schemas/ApiKeyCredentials'
        - $ref: '#/components/schemas/Oauth2Credentials'
        - $ref: '#/components/schemas/ServiceAccountCredentials'
    Oauth2Credentials:
      type: object
      properties:
        type:
          type: string
          enum: [oauth2]
        domain:
          type: string
        accounts:
          type: array
          items:
            type: string
            format: uuid
        operations:
          type: array
          items:
            type: string
    ApiKeyCredentials:
      type: object
      properties:
        type:
          type: string
          enum: [api_key]
        accounts:
          type: array
          items:
            type: string
            format: uuid
        address:
          type: string
        operations:
          type: array
          items:
            type: string
        expire_at:
          type: string
    ServiceAccountCredentials:
      type: object
      properties:
        type:
          type: string
          enum: [api_key]
        accounts:
          type: array
          items:
            type: string
            format: uuid
        operations:
          type: array
          items:
            type: string
    Role:
      type: object
      properties:
        permissions:
          type: array
          items:
            type: string


